arch:
  - amd64
  - arm64 

branches:
  only:
    - master
    - develop

gemfile: Gemfile.ci

language: ruby

os:
  - linux

rvm:
  - ruby-head
  - 2.7
  - 2.6
  - 2.5
  - 2.4
  - 2.3
  - 2.2
  - 2.1
  - 2.0
  - 1.9
  - 1.8
  - rbx-3
  - rbx-2
  - truffleruby
