language: ruby
rvm:
  - ruby-head
  - ruby-head-clang
  - 2.5.0
  - 2.4.3
  - 2.3.6
  - 2.2.9
  - 2.1.10
  - 2.0.0-p648
  - 1.9.3-p551
  - 1.9.2
  - 1.8.7
  - rbx-3
  - rbx-2

gemfile: Gemfile.ci

branches:
  only:
    - master

os:
  - linux
  - osx
